spring:
  application:
    name: app-microservice-location-producer
  webflux:
    base-path: /app-microservice-auth
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/landscapedb
    username: landscape
    password: landscape


server:
  port: 8001

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_KEY:MsUEV8IkLNB7NkFB0iVHtaCNrn98CTzYIz/5w4te3J0=}
  expiration: 86400000  # 24 horas en milisegundos


minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: landscapes