spring:
  application:
    name: app-microservice-location-producer
  webflux:
    base-path: /app-microservice-auth

server:
  port: 8080

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
